import Footer from "@/components/module/common/client/Footer"
import RegisterHeader from "@/components/module/common/server/registerHeader"
import LeftNav from "@/components/module/user/Physician/Sidebar"
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";

// export const metadata = {
//     title: 'Physician',
//     description: 'Generated by create next app',
// }
// export const Metadata=()=>{
//    return{
//     title: 'Physician',
//     description: 'Generated by create next app',
//    }
// }
export async function generateMetadata(
    ){
         const data = await getServerSession(authOptions);
      return {
        title: `${data?.user?.role_id ==="8"?"Expert":"Physician"}`,
        description: 'Generated by create next app',
      }
    }

export default async function PhysicianLayout({ children }) {
    return (
        <div className="App">
            <RegisterHeader />
            <div className='loggedin-bg flex items-start'>
                <LeftNav />
                {children}
            </div>
            <Footer />
        </div>
    )
}