import Tabs from '@/components/module/user/lawfirm/AccountSettings/Tabs';
import { authOptions } from '@/lib/auth';
import { getServerSession } from 'next-auth';

export async function generateMetadata(
  ){
       const data = await getServerSession(authOptions);
    return {
      title: `${data?.user?.role_id ==="6"?"AttorneyAssistant":"Attorney"} Account Setting`,
      description: 'Generated by create next app',
    }
  }

export default async function LawfirmAccountSettingsLayout({ children }) {
  return (
    <div className="right-container !flex-[0_0_calc(100vw-21.5625rem)] max-w-[calc(100vw-21.5625rem)] !pb-0 min-h-[100vh]">
      <div className="flex items-center min-h-12 mb-6">
        <h2 className="c-page-title !mb-0">Account Settings</h2>
      </div>
      <div className="m-card">
        <div className="m-card-top">
          <Tabs />
        </div>
        {children}
      </div>
    </div>
  );
}
