import Footer from "@/components/module/common/client/Footer"
import RegisterHeader from "@/components/module/common/server/registerHeader"
import LeftNav from "@/components/module/user/CourtReporter/Sidebar"

export const metadata = {
    title: 'Court Reporter',
    description: 'Generated by create next app',
}

export default async function PhysicianLayout({ children }) {
    return (
        <div className="App">
            <RegisterHeader />
            <div className='loggedin-bg flex items-start'>
                <LeftNav />
                {children}
            </div>
            <Footer />
        </div>
    )
}